version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.4 # Use a specific version tag (tag latest is not published)
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /opt/mailman/core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgresql://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    - SMTP_PORT=25
    - SMTP_HOST=smtp.usm.edu
    - MTA=postfix
    ports:
    #- "127.0.0.1:8001:8001" # API
    #- "127.0.0.1:8024:8024" # LMTP - incoming email
    networks:
      mailman:

  mailman-web:
    image: maxking/mailman-web:0.4 # Use a specific version tag (tag latest is not published)
    container_name: mailman-web
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgresql://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SECRET_KEY=t9jhp)+8ts##r*gql7(hc9f)u)0#ctprz3cxy!+3f#sci)-38l
    - SMTP_PORT=25
    - SMTP_HOST=smtp.usm.edu
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    - SERVE_FROM_DOMAIN=lists.usm.edu
    - MAILMAN_ADMIN_USER=admin
    - MAILMAN_ADMIN_EMAIL=tony.deshields@usm.edu
    ports:
    #- "127.0.0.1:8000:8000" # HTTP
    #- "127.0.0.1:8080:8080" # uwsgi
    networks:
      mailman:

  mailman-nginx:
    image: docker.io/library/nginx:latest
    container_name: mailman-nginx
    hostname: mailman-nginx
    volumes:
    - /opt/mailman/nginx/conf.d:/etc/nginx/conf.d
    - /opt/mailman/ssl:/etc/ssl/certs
    links:
    - mailman-web:mailman-web
    depends_on:
    - mailman-web
    ports:
    - "443:443" # HTTPS
    networks:
      mailman:
      

  database:
    environment:
    - POSTGRES_DB=mailmandb
    - POSTGRES_USER=mailman
    - POSTGRES_PASSWORD=mailmanpass
    image: postgres:11-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    networks:
      mailman:

networks:
  mailman:
